name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go install -v gotest.tools/gotestsum@latest
          go get -d github.com/boumenot/gocover-cobertura@latest
          go install github.com/boumenot/gocover-cobertura@latest
          go get -d github.com/ggere/gototal-cobertura@latest
          go install github.com/ggere/gototal-cobertura@latest
      - name: Linting
        run: |
          go vet ./...
          golint -set_exit_status=0 ./...
      - name: Run tests with coverage
        run: |
          gotestsum --format testname --junitfile unit-tests.xml -- -coverprofile=coverage.out ./...
          gocover-cobertura < coverage.out > cobertura-coverage.xml
          gototal-cobertura < cobertura-coverage.xml
          go tool cover -html=coverage.out -o cobertura-coverage.html
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests.xml
          path: unit-tests.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: unit-tests.xml
      - name: Upload coverage report XML
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-coverage.xml
          path: cobertura-coverage.xml
      - name: Coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: cobertura-coverage.xml
          minimum_coverage: 75
